use_frameworks!

target 'SSAppUpdater_Example' do
  pod 'SSAppUpdater', :path => '../'

  target 'SSAppUpdater_Tests' do
    inherit! :search_paths

    
  end
end

target 'SSAppUpdaterMac_Example' do
  pod 'SSAppUpdater', :path => '../'
end
