//
//  SSScriptOrCommandExecutor.swift
//  Pods
//
//  Created by Rishita Panchal on 28/08/24.
//

import Foundation

#if os(macOS)
enum SSScriptOrCommandExecutor {
    /**
     Executes a command in the terminal and returns the output as a string.
     - Parameter cmd: A string representing the command to be executed in the terminal.

     - Returns: An optional string containing the output generated by executing the command. If the command execution fails or returns no output, nil is returned.
    */
    static func executeCommand(_ cmd: String) -> String? {
        let pipe = Pipe()
        let process = Process()
        process.launchPath = "/bin/sh"
        process.arguments = ["-c", String(format: "%@", cmd)]
        process.standardOutput = pipe
        let fileHandle = pipe.fileHandleForReading
        process.launch()
        return String(data: fileHandle.readDataToEndOfFile(), encoding: .utf8)
    }
}
#endif
